[package]
name = "simt_rocblas_sys"
version = "0.1.0"
edition = "2021"
description = "part of simt. rocBLAS api bindings"
authors = ["Mack Straight <mack@str.rs>"]
license = "MIT"

[dependencies]
libloading = "0.8.0"
