[package]
name = "simt_hip"
version = "0.1.6"
edition = "2021"
license = "MIT"
description = "part of simt. amd rocm/hip backend"
authors = ["Mack Straight <mack@str.rs>"]

[dependencies]
half = "2.3.1"
simt_hip_sys = { version = "0.1.2", path = "../simt_hip_sys" }
thiserror = "1"
