[package]
name = "simt_cuda"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "part of simt. cuda backend"
authors = ["Mack Straight <mack@str.rs>"]

[dependencies]
half = "2.3.1"
simt_cuda_sys = { version = "0.1.2", path = "../simt_cuda_sys" }
thiserror = "1"
